### ISSUE TITLE
Bad practice of using global variable in a mixin

### ISSUE THREAD

**Issue by KittyGiraudel** [cole007/better-css-with-sass#13]
## Fix

Change:

``` scss
$base-font-size: 16;
@mixin font-size($size) {
  font-size: $size + px;
  font-size: ($size / $base-font-size) + rem; }
```

Into:

``` scss
@mixin font-size($size, $base-font-size: 16) {
  font-size: $size + px;
  font-size: ($size / $base-font-size) + rem; }
```
## Pages
- 40
