### ISSUE TITLE
incorrect nesting when explaining BEM

### ISSUE THREAD

**Issue by KittyGiraudel** [cole007/better-css-with-sass#8]
I think you are already aware of this one.
## Fix

Change:

``` scss
.article {
margin: 20px 0;
  &__image {
    width: 40%; }
  &--small {
    width: 20%; }}
```

Into:

``` scss
.article {
margin: 20px 0;
  &__image {
    width: 40%;
    &--small {
      width: 20%; }}}
```
## Pages
- 30
